### ISSUE TITLE
[Question] Setup problems

### ISSUE THREAD

**Issue by Starbors** [vn7n24fzkq/github-profile-summary-cards#11]
So l did follow everything and it still does not work great!

**Comment by vn7n24fzkq** [comment]
Thanks for report.
Seems you don't use the secrets key correctly,  make sure the personal access token is added to your repo secrets.
The GITHUB_TOKEN should be `secrets.`  append with the name of secret instead of value.
```
 env:
     GITHUB_TOKEN: ${{ secrets.README }}
```
Here is how looks if the personal access token  added to repo secrets.
![image](https://user-images.githubusercontent.com/20241522/94542614-95a84d00-027b-11eb-8494-973f90895723.png)

And make sure the personal access token has these permission.
[Permissions](https://github.com/vn7n24fzkq/github-profile-summary-cards/wiki/Personal-access-token-permissions)

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

**Comment by Starbors** [comment]
Soooo
 env:
     GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

Or like
 env:
     MY_TOKEN: ${{ secrets.README }}
Or
 env:
     GITHUB_TOKEN: ${{ MY_TOKEN.README }}
I really dont get it lol

**Comment by vn7n24fzkq** [comment]
You need to new a secret in repo secrets, and you can name it by self but secret's value need to be personal access token value.
![image](https://user-images.githubusercontent.com/20241522/94544858-5deed480-027e-11eb-9944-bdfa07882420.png)

**Comment by vn7n24fzkq** [comment]
Not sure, but in your repo the secret looks like token value instead of secret name. 🤔
https://github.com/Starbors/starbors/blob/0ffa36e11dad70a2cbec9b1dfe491ed13d1aa746/.github/workflows/profile-summary-cards.yml#L19

**Comment by Starbors** [comment]
ahh l see

**Comment by Starbors** [comment]
it is still not working and l did what you told me in the settings

**Comment by vn7n24fzkq** [comment]
Do you add your personal access token as secret to your repo? 😕

**Comment by vn7n24fzkq** [comment]
@Starbors , this is not a bug actually so I rename this issue, hope you don't mind.

**Comment by Starbors** [comment]
oh ye lol sorry!

**Comment by Starbors** [comment]
> Did you add your personal access token as secret to your repo? 😕
> And you will need these permission.
> ![image](https://user-images.githubusercontent.com/20241522/94668082-2fd2c880-0342-11eb-85d0-5df9bdc7fcd8.png)
> ![image](https://user-images.githubusercontent.com/20241522/94668096-33fee600-0342-11eb-9bfc-f6681eddd4dd.png)

Yes and l even added more perms

**Comment by vn7n24fzkq** [comment]
That's weird.
I have checked the last result of your github action.
401 is meaning the request was Unauthorized.
Maybe the secret doesn't add to your repo?

Can you run the action again?

**Comment by Starbors** [comment]
Yes

**Comment by Starbors** [comment]
So wait l did add everything and l added [![](https://raw.githubusercontent.com/vn7n24fzkq/github-profile-summary-cards-example/master/profile-summary-card-output/solarized_dark/3-stats.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)
and the others but changed 
vn7n24fzkq --> starbors
Which didnt fix anything what should l do at this point

**Comment by vn7n24fzkq** [comment]
@Starbors.
I forked your repo and check action setting. It is can work if the secret has already setup.
See here. https://github.com/vn7n24fzkq/starbors/tree/main/profile-summary-card-output
Maybe this article can help you.
https://dev.to/susomejias/use-token-for-github-actions-with-private-repositories-22m6
And here is offical doc for repo secrets.
https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

**Comment by Starbors** [comment]
AHh tysm!

**Comment by vn7n24fzkq** [comment]
You are welcome.
Please let me know if you still have any issues.

**Comment by Starbors** [comment]
soo l more problem 
>:) tysm for all the support
`
[![](https://raw.githubusercontent.com/starbors/starbors/main/profile-summary-card-output/vue/0-profile-details.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)
[![](https://raw.githubusercontent.com/starbors/starbors/main/profile-summary-card-output/vue/1-repos-per-language.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)
[![](https://raw.githubusercontent.com/starbors/starbors/main/profile-summary-card-output/vue/3-stats.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)
`
Why does only 1 work?
[![](https://raw.githubusercontent.com/starbors/starbors/main/profile-summary-card-output/vue/3-stats.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)

**Comment by vn7n24fzkq** [comment]
This action generate numbers of cards with different theme into your repo actually, you can find those cards in profile-summary-card-output folder in the repo which setup this action.

It will generate all cards each action.
If generate get exception or error then skip to next card generating, until action finished.

Some people's GITHUB_TOKEN doesn't has permission for all github api and I don't know why, the solution is use the personal access token they owned instead GITHUB_TOKEN in github action.

I guess your problem is you don't set up repo secret correctly.
