### ISSUE TITLE
Graph dippes to zero with wrong measure

### ISSUE THREAD

**Issue by felipejoribeiro** [vn7n24fzkq/github-profile-summary-cards#28]
**Describe the bug**
Suddenly the graph dipped to zero. 
But this don't reflect real productivity.

**To Reproduce**
1. Even in this profile ( https://github.com/vn7n24fzkq ) the bug is present.

**Expected behavior**
Normal behavior, reflecting GitHub contributions. 

**Screenshots**

![image](https://user-images.githubusercontent.com/39244876/106473662-cc3ce100-6482-11eb-9c51-cb433abbdc21.png)

![image](https://user-images.githubusercontent.com/39244876/106473619-bd562e80-6482-11eb-85b1-7c140cb3ca45.png)

**Desktop (please complete the following information):**
 - Browser [any]

**Additional context**
Seems to be a general problem (?)

**Comment by vn7n24fzkq** [comment]
Thanks for your report.
I guess because the card was generated before first contribute in February.

Maybe we can wait until next execution occur and check if the graph still dip to zero?
Or you can trigger the action manually. ( I have not any contribution in February yet )

**Comment by felipejoribeiro** [comment]
@vn7n24fzkq  thanks for the kind and prompt response. 
I did trigger the action manually, with a new commit done to the reade-me but it did not solve the problem.

**Comment by vn7n24fzkq** [comment]
@felipejoribeiro 
I had check your SVG raw file, and seems it already generate the graph normally.
Because GitHub use cache for raw file, the readme might not be updated in time.

https://github.com/felipejoribeiro/felipejoribeiro/blob/master/profile-summary-card-output/default/0-profile-details.svg
![image](https://user-images.githubusercontent.com/20241522/106491946-5bcda880-64f2-11eb-831a-698112d469b7.png)

Because the value of February is 6 and the y-axis tick is 20 so it looks close to zero.

**Comment by felipejoribeiro** [comment]
I see. Thank you very much!
Awesome!
Best regards

**Comment by vn7n24fzkq** [comment]
Thank you too.
Maybe we can enhance visual effects on this part in the future.

I will close issue if there no other problems.

**Comment by felipejoribeiro** [comment]
All right.
I think that's all. 
Best regards.
